name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node packages
      env:
        NODE_ENV: development
      run: |
        npm ci --silent
    - name: Run all pre-release checks and validate no changed files
      run: |
        npm run pre-release
        [[ -z $(git status -s) ]] || (git status -s; echo "changes to files in CI"; exit 1);
